### ISSUE TITLE
Command failed with exit code 1: npm info 'prettier@^3.0.3' --json

### ISSUE THREAD

**Issue by bracke** [IgnaceMaes/ember-addon-v2-scanner#1]
After running npx ember-addon-v2-scanner@latest
I get the following error:

```javascript 
Inspecting ember-yeti-tablefile:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/execa/lib/return/final-error.js:6
        return new ErrorClass(message, options);
               ^

ExecaError: Command failed with exit code 1: npm info 'prettier@^3.0.3' --json

npm ERR! maxAge must be a number
{
  "error": {
    "code": null,
    "summary": "maxAge must be a number",
    "detail": ""
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bent/.npm/_logs/2024-06-17T06_13_44_690Z-debug-0.log
    at getFinalError (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/execa/lib/methods/main-async.js:174:4)
    at handlePromise (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/execa/lib/methods/main-async.js:157:17)
    at async getPackageInfo (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/ember-addon-v2-scanner/bin.js:34:22)
    at async processDep (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/ember-addon-v2-scanner/bin.js:87:16)
    at async Promise.all (index 8)
    at async prepareBatch (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/ember-addon-v2-scanner/bin.js:111:5)
    at async traverseGraph (file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/ember-addon-v2-scanner/bin.js:124:5)
    at async file:///home/bent/.npm/_npx/8df82c54c902fe6c/node_modules/ember-addon-v2-scanner/bin.js:135:1 {
  shortMessage: "Command failed with exit code 1: npm info 'prettier@^3.0.3' --json",
  command: 'npm info prettier@^3.0.3 --json',
  escapedCommand: "npm info 'prettier@^3.0.3' --json",
  cwd: '/home/bent/Projekter/boel',
  durationMs: 543.655315,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  exitCode: 1,
  stdout: '',
  stderr: 'npm ERR! maxAge must be a number\n' +
    '{\n' +
    '  "error": {\n' +
    '    "code": null,\n' +
    '    "summary": "maxAge must be a number",\n' +
    '    "detail": ""\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/bent/.npm/_logs/2024-06-17T06_13_44_690Z-debug-0.log',
  stdio: [
    undefined,
    '',
    'npm ERR! maxAge must be a number\n' +
      '{\n' +
      '  "error": {\n' +
      '    "code": null,\n' +
      '    "summary": "maxAge must be a number",\n' +
      '    "detail": ""\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'npm ERR! A complete log of this run can be found in:\n' +
      'npm ERR!     /home/bent/.npm/_logs/2024-06-17T06_13_44_690Z-debug-0.log'
  ],
  ipcOutput: [],
  pipedFrom: []
}

Node.js v20.11.1
```

**Comment by bracke** [comment]
Deleting node_modules and lock file fixed it - sorry for the noise.
